#!/data/data/com.termux/files/usr/bin/bash
# Auto gelud
# coded By ./Droid
Clear

blue='\e[0;34'
cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
toilet -f big -F gay "T.HUNTER" | lolcat
###################################################
# CTRL C
###################################################
trap ctXrl_c INT
ctrl_c() {
clear
echo -e $gold"[#]> (Ctrl + C ) Detected, Trying To Exit ... "
sleep 1
echo ""
echo -e $blue"[#]> semoga bermanfaat "
sleep 1
echo ""
read enter
exit
}
echo "" 
echo "================================================"     
echo "=Author : ./Droid_X_ISH&Tn.Chaplin&Kuro Cyber  =" 
echo "=Team   : Indonesian Security Hunter           ="
echo "=Kontak : 089606402413                         ="
echo "=Date   :05-06-2018                            ="
echo "================================================"
echo -e $blue" 01) Red Hawk"
echo -e $yellow" 02) D-Tect"
echo -e $green" 03) Hunner"
echo -e $black" 04) WPScan"
echo -e $red" 05) Webdav"
echo -e $white" 06) Metasploit"
echo -e $purple" 07) Kali Nethunter"
echo -e $green" 08) Ubuntu"
echo -e $red" 09) Youtube Dl"
echo -e $gold" 10) viSQL "
echo -e $yellow" 11) WFDroid"
echo -e $purple" 12) FBBrute"
echo -e $white" 13) Ngrok"
echo -e $green" 14) Torshammer"
echo -e $blue" 00) crotz"
echo -e $white""
read -p "[T.HUNTER==> " act;

if [ $act = 01 ] || [ $act = 01 ]
then
clear
echo -e $green" Installing Red Hawk "
sleep 1
apt update && apt upgrade
apt install php
apt install git
git clone https://github.com/Tuhinshubhra/RED_HAWK
echo -e $green" selesai tod "
fi

if [ $act = 02 ] || [ $act = 02 ]
then
clear
echo -e $green" Installing D-Tect "
sleep 1
apt-get update && apt-get upgrade
apt-get install git
apt-get install python2
git clone https://github.com/shawarkhanethicalhacker/D-TECT
echo -e $red" crot didalem "
fi

if [ $act = 03 ] || [ $act = 03 ]
then
clear
echo -e $green" Installing Hunner "
sleep 1
apt-get update && apt-get upgrade
apt install python
apt install git
git clone https://github.com/b3-v3r/Hunner
echo -e $red" anda beruntung "
fi

if [ $act = 04 ] || [ $act = 04 ]
then
clear
echo -e $green" Installing Wpscan "
sleep 1
apt-get update && apt-get upgrade
apt install ruby
apt install curl
apt install git
git clone https://github.com/wpscanteam/wpscan
cd ~/wpscan
gem install bundle
bundle config build.nokogiri --use-system-libraries
bundle install
ruby wpscan.rb --update
cd ~/
echo -e $red" eaa berhasil "
fi

if [ $act = 05 ] || [ $act = 05 ]
then
clear
echo -e $green" Installing Webdav "
sleep 1
apt update && apt upgrade
apt install python2
pip2 install urllib3 chardet certifi idna requests
apt install openssl curl
pkg install libcurl
mkdir webdav
cd ~/webdav
wget https://pastebin.com/raw/HnVyQPtR -O webdav.py
chmod 777 webdav.py
cd ~/
echo -e $red" kamu dapet perawan "
fi

if [ $act = 06 ] || [ $act = 06 ]
then
clear
echo -e $green" Installing Metasploit "
sleep 1
apt update && apt upgrade
apt install git
apt install wget
wget https://raw.githubusercontent.com/verluchie/termux-metasploit/master/install.sh
chmod 777 install.sh
sh install.sh
echo -e $red" Done Install "
fi

if [ $act = 07 ] || [ $act = 07 ]
then
clear
echo -e $green" Installing Kali Nethunter "
sleep 1
apt update && apt upgrade
apt install git
git clone https://github.com/Hax4us/Nethunter-In-Termux.git
cd ~/Nethunter-In-Termux
chmod 777 kalinethunter
sh kalinethunter
echo -e $red" kamu milea ya "
fi

if [ $act = 08 ] || [ $act = 08 ]
then
clear
echo -e $green" Installing Ubuntu "
sleep 1
apt update && apt upgrade
apt install git
apt install wget
apt install proot
git clone https://github.com/Neo-Oli/termux-ubuntu.git
cd ~/termux-ubuntu
chmod +x ubuntu.sh
sh ubuntu.sh
echo " Fix network please wait "
sleep 1
echo "nameserver 8.8.8.8" > /data/data/com.termux/files/home/termux-ubuntu/ubuntu-fs/etc/resolv.conf
echo -e $red" selesai tod "
fi

if [ $act = 09 ] || [ $act = 09 ]
then
clear
echo -e $green" Installing Youtube DL "
sleep 1
apt update && apt upgrade
apt install python
pip3 install mps_youtube
pip3 install youtube_dl
apt install mpv
echo " Untuk menjalankannya ketik "mpsyt" tanpa tanda petik "
echo -e $red" selesai "
fi

if [ $act = 10 ] || [ $act = 10 ]
then
clear
echo -e $green" Installing viSQL "
sleep 1
apt update && apt upgrade
pkg install git
pkg install python2
git clone https://github.com/blackvkng/viSQL.git
cd ~/viSQL
chmod 777 viSQL.py
cd ~/viSQL
echo -e $red" selesai tod "
fi

if [ $act = 11 ] || [ $act = 11 ]
then
clear
echo -e $green" Installing WFDroid "
sleep 1
apt update && apt upgrade
apt install wget
mkdir wfdroid
cd ~/wfdroid
wget https://raw.githubusercontent.com/bytezcrew/wfdroid-termux/master/wfdinstall
chmod 777 wfdinstall
sh wfdinstall
cd ~/
echo -e $red" selesai tod "
fi

if [ $act = 12 ] || [ $act = 12 ]
then
clear
sleep 1
echo -e $green" Installing FBBrute "
apt install python2
apt install python2-dev
apt install wget
pip2 install mechanize
mkdir fbbrute
cd ~/fbbrute
wget https://pastebin.com/raw/aqMBt2xA -O fbbrute.py
wget http://override.waper.co/files/password.apk
mv password.apk password.txt
chmod 777 fbbrute.py
cd ~/
echo -e $red" cie crotz "
fi

if [ $act = 13 ] || [ $act = 13 ]
then
clear
echo -e $green" Installing Ngrok "
sleep 1
apt install wget
mkdir ngrok
cd ~/ngrok
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip
unzip ngrok-stable-linux-arm.zip
cd ~/
echo -e $red" dah eaaa "
fi

if [ $act = 14 ] || [ $act = 14 ]
then
clear
echo -e $green" Installing Hammer "
sleep 1
pkg update
pkg upgrade
pkg install python
pkg install git
git clone https://github.com/cyweb/hammer
cd ~/
echo -e $red" guud "
fi

if [ $act = 00 ] || [ $act = 00 ]
then
echo -e $green" thanks udah mau nyoba "
sleep 1
echo -e $yellow" ISH was here "
sleep 1
echo -e $gold" mungkin agak sakit.... "
sleep 1
exit
fi
